/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import controller.BLLChiTietDichVu;
import controller.BLLDichVu;
import controller.BLLPhong;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import model.printDichVu;
import object.ChiTietDichVu;
import object.DichVu;
import object.Phong;

/**
 *
 * @author Nguyen Hoang Giang
 */
public class BanHang extends javax.swing.JFrame {

    /**
     * Creates new form BanHang
     */
    BLLDichVu bllDichVu;
    ArrayList<ChiTietDichVu> dsChiTietDichVuDung;
    ArrayList<DichVu> dsDichVuDung;
    ArrayList<DichVu> dsDichVuTamThoi;
    ArrayList<ChiTietDichVu> dsChiTietDichVuTamThoi;
    String maDatPhong = QuanLyKhachSan.maDatPhong;
    String maHoaDon = QuanLyKhachSan.maHoaDon;
    String maPhong = QuanLyKhachSan.maPhong;
    Integer tongTien = 0;
    Integer tienTra = 0;

    public BanHang() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception ex) {
        }
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setVisible(true);
        System.out.println("Ma Dat Phong:" + maDatPhong);
        System.out.println("Ma Hoa Don:" + maHoaDon);
        System.out.println("Ma Phong:" + maPhong);
        bllDichVu = new BLLDichVu();
        hienThiDichVuLenBangDichVuTuArrayList(bllDichVu.layToanBoDichVu());
        dsChiTietDichVuDung = layChiTietDichVuDaDung(maDatPhong, maHoaDon, maPhong);
        dsChiTietDichVuTamThoi = layChiTietDichVuDaDung(maDatPhong, maHoaDon, maPhong);
        dsDichVuDung = layDanhSachDichVuDaDung(dsChiTietDichVuDung);
        dsDichVuTamThoi = layDanhSachDichVuDaDung(dsChiTietDichVuDung);
        hienThiThongTinDichVuCuaPhong(dsChiTietDichVuTamThoi, dsDichVuTamThoi);
        jTextField5.setText(maPhong);
        Color col = jPanel1.getBackground();
    }

    private void hienThiTien() {
        jTextField1.setText(tongTien + " VND");
    }

    private ArrayList<ChiTietDichVu> layChiTietDichVuDaDung(String maDatPhong, String maHoaDon, String maPhong) {
        return BLLChiTietDichVu.layToanBoDichVu(maDatPhong, maHoaDon, maPhong);
    }

    private ArrayList<DichVu> layDanhSachDichVuDaDung(ArrayList<ChiTietDichVu> dsChiTiet) {
        ArrayList<DichVu> dsDichVu = new ArrayList<>();
        for (ChiTietDichVu ct : dsChiTiet) {
            DichVu dv = bllDichVu.timKiemDichVu(ct.getMaDichVu());
            dsDichVu.add(dv);
        }
        return dsDichVu;
    }

    private void hienThiThongTinDichVuCuaPhong(ArrayList<ChiTietDichVu> dsChiTiet, ArrayList<DichVu> dsDichVu) {
        tongTien = 0;
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Mã dịch vụ");
        dtm.addColumn("Tên dịch vụ");
        dtm.addColumn("Số lượng");
        dtm.addColumn("Đơn giá");
        dtm.addColumn("Thành tiền");
        for (int i = 0; i < dsChiTiet.size(); i++) {
            ChiTietDichVu ct = dsChiTiet.get(i);
            DichVu dv = dsDichVu.get(i);
            Vector<String> v = new Vector<>();
            v.add(dv.getMaDichVu());
            v.add(dv.getTenDichVu());
            Integer soLuong = ct.getSoLuong();
            v.add(soLuong + "");
            Integer donGia = dv.getGiaDichVu();
            v.add(donGia + " VND");
            Integer thanhTien = donGia * soLuong;
            tongTien += thanhTien;
            v.add(thanhTien + " VND");
            dtm.addRow(v);
            System.out.println("Mã dịch vụ: " + ct.getMaDichVu() + " " + ct.getMaDatPhong() + " " + ct.getMaHoaDon() + " " + ct.getMaPhong() + " " + ct.getSoLuong());
        }
        jTable1.setModel(dtm);
        hienThiTien();
    }

    private void hienThiDichVuLenBangDichVuTuArrayList(ArrayList<DichVu> ds) {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Mã dịch vụ");
        dtm.addColumn("Tên dịch vụ");
        dtm.addColumn("Đơn giá");
        for (DichVu dv : ds) {
            Vector<String> v = new Vector<>();
            v.add(dv.getMaDichVu());
            v.add(dv.getTenDichVu());
            v.add(dv.getGiaDichVu() + " VND");
            dtm.addRow(v);
        }
        jTable2.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bán Hàng");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Dịch Vụ:", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã DV", "Tên DV", "Đơn Giá"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Giỏ Hàng:", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jPanel3.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Dịch Vụ", "Tên Dịch Vụ", "Số Lượng", "Đơn Giá", "Thành Tiền"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("Xóa Khỏi Giỏ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Thêm Vào Giỏ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel3.setText("Số Lượng:");

        txtSoLuong.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton5)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setText("Phòng:");

        jLabel2.setText("Tổng Tiền:");

        jTextField1.setEditable(false);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButton1.setText("Lưu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Thoát");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Dịch Vụ:");

        jButton4.setText("Tìm Kiếm");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("Toàn Bộ DV");

        jTextField5.setEditable(false);
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField5.setText("jTextField5");

        jCheckBox1.setText("In Phiếu Dịch Vụ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addComponent(jLabel2)
                                        .addGap(201, 201, 201))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(152, 152, 152)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jTextField1))))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addGap(95, 95, 95))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (jTextField4.getText().matches("\\s*")) {
            JOptionPane.showMessageDialog(null, "Hãy nhập tên dịch vụ muốn tìm kiếm.");
            return;
        }
        ArrayList<DichVu> dsTimKiem = bllDichVu.timKiemDichVu(jTextField4.getText(), "", "");
        hienThiDichVuLenBangDichVuTuArrayList(dsTimKiem);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int[] rowChon = jTable2.getSelectedRows();
        if (rowChon.length <= 0) {
            JOptionPane.showMessageDialog(null, "Hãy chọn dịch vụ muốn thêm.");
        } else {
            for (int i : rowChon) {
                DichVu dv = new DichVu();
                ChiTietDichVu ct = new ChiTietDichVu();
                String maDichVu = jTable2.getValueAt(i, 0) + "";
                dv.setMaDichVu(maDichVu);
                ct.setMaDichVu(maDichVu);
                try {
                    dv.setTenDichVu(jTable2.getValueAt(i, 1) + "");
                    String strGia = jTable2.getValueAt(i, 2) + "";
                    Integer gia = Integer.parseInt(strGia.substring(0, strGia.length() - 4));
                    dv.setGiaDichVu(gia);
                } catch (Exception e) {
                    e.printStackTrace();
                }
                ct.setMaDatPhong(maDatPhong);
                ct.setMaHoaDon(maHoaDon);
                ct.setMaPhong(maPhong);
                if (dsChiTietDichVuTamThoi.contains(ct)) {
                    for (ChiTietDichVu chiTiet : dsChiTietDichVuTamThoi) {
                        if (ct.equals(chiTiet)) {
                            int soLuong = chiTiet.getSoLuong();
//                            soLuong++;
                            try {
                                int soLuongThem = 1;
                                if (txtSoLuong.getText().matches("\\d+")) {
                                    soLuongThem = Integer.parseInt(txtSoLuong.getText());
                                }
                                soLuong += soLuongThem;
                            } catch (Exception e) {

                            }
                            chiTiet.setSoLuong(soLuong);
                            break;
                        }
                    }
                } else {
                    ct.setSoLuong(1);
                    dsDichVuTamThoi.add(dv);
                    dsChiTietDichVuTamThoi.add(ct);
                }

            }
            hienThiThongTinDichVuCuaPhong(dsChiTietDichVuTamThoi, dsDichVuTamThoi);
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int[] rowChon = jTable1.getSelectedRows();
        if (rowChon.length <= 0) {
            JOptionPane.showMessageDialog(null, "Hãy chọn dịch vụ từ giỏ muốn xóa");
        } else {
            for (int i = rowChon.length - 1; i >= 0; i--) {
                int viTri = rowChon[i];
                ChiTietDichVu ct = dsChiTietDichVuTamThoi.get(rowChon[i]);
                DichVu dv = dsDichVuTamThoi.get(rowChon[i]);
                try {
                    String strSoLuong = jTable1.getValueAt(rowChon[i], 2) + "";
                    Integer soLuong = Integer.parseInt(strSoLuong);
                    System.out.println("Số lượng: " + soLuong);
                    if (dsChiTietDichVuDung.contains(ct)) {
                        int soLuongDaDung = 0;
                        for (ChiTietDichVu c : dsChiTietDichVuDung) {
                            if (c.equals(ct)) {
                                soLuongDaDung = c.getSoLuong();
                                break;
                            }
                        }
                        try {
                            int soLuongXoa = 1;
                            if (txtSoLuong.getText().matches("\\d+")) {
                                soLuongXoa = Integer.parseInt(txtSoLuong.getText());
                            }
                            soLuong -= soLuongXoa;
                            if (soLuong < soLuongDaDung) {
                                JOptionPane.showMessageDialog(null, "Phòng " + maPhong + " đã đăng ký sử dụng " + soLuongDaDung + " " + dv.getTenDichVu() + " trước đó.");
                                return;
                            } else {
//                                soLuong--;
                                ct.setSoLuong(soLuong);
                            }
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    } else {
                        if (soLuong == 1) {
                            System.out.println("Xóa" + dv.getTenDichVu());
                            dsChiTietDichVuTamThoi.remove(ct);
                            dsDichVuTamThoi.remove(dv);
                        } else {
                            System.out.println(dv.getTenDichVu() + "Trừ 1");
                            soLuong--;
                            ct.setSoLuong(soLuong);
                        }
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
            hienThiThongTinDichVuCuaPhong(dsChiTietDichVuTamThoi, dsDichVuTamThoi);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int xacNhan = JOptionPane.showConfirmDialog(null, "Bạn có muốn lưu lại thông tin vừa thay đổi", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (xacNhan == JOptionPane.YES_OPTION) {
            for (ChiTietDichVu ct : dsChiTietDichVuTamThoi) {
                if (dsChiTietDichVuDung.contains(ct)) {
                    BLLChiTietDichVu.suaSoLuong(ct.getMaDatPhong(), ct.getMaHoaDon(), ct.getMaDichVu(), ct.getMaPhong(), ct.getSoLuong());
                    System.out.println("Sửa");
                } else {
                    BLLChiTietDichVu.themChiTietMuonTra(ct.getMaDatPhong(), ct.getMaHoaDon(), ct.getMaDichVu(), ct.getMaPhong(), ct.getSoLuong());
                    System.out.println("Thêm");
                }
            }
            JOptionPane.showMessageDialog(null, "Thay đổi thành công");
            if (jCheckBox1.isSelected() == true) {
                this.dispose();
                printDichVu.inPhieuDichVu(maDatPhong, maHoaDon, maPhong, tongTien + "");
            } else {
                this.dispose();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int xacNhan = JOptionPane.showConfirmDialog(null, "Bạn có muốn thoát ? Nếu bạn thoát, mọi thay đổi vừa rồi sẽ không có hiệu lực.", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (xacNhan == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "Mọi thay đổi vừa rồi của bạn sẽ không có hiệu lực.");
            this.dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BanHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables
}
