/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import controller.BLLKhachHang;
import controller.KiemTraDuLieuNhapThoaMan;
import controller.TaoMaTiepTheo;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import model.printKhachHang;
import object.KhachHang;

/**
 *
 * @author Nguyen Hoang Giang
 */
public class QuanLyKhachHangUI extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyKhachHangUI
     */
    private DefaultTableModel dtmQuanLyKhachHang = new DefaultTableModel();
    private DefaultTableModel dtmTimKiemKhachHang = new DefaultTableModel();
    TaoMaTiepTheo taoMa = new TaoMaTiepTheo();
    BLLKhachHang bllKhachHang = new BLLKhachHang();
    JButton btnLast;

    public QuanLyKhachHangUI() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception ex) {
        }
        initComponents();
        this.setLocationRelativeTo(null);
        dtmQuanLyKhachHang.addColumn("Mã khách hàng");
        dtmQuanLyKhachHang.addColumn("Tên khách hàng");
        dtmQuanLyKhachHang.addColumn("Giới tính");
        dtmQuanLyKhachHang.addColumn("SĐT");
        dtmQuanLyKhachHang.addColumn("CMND");
        dtmQuanLyKhachHang.addColumn("Địa chỉ");
        tblQuanLyKhachHang.setModel(dtmQuanLyKhachHang);
        DefaultComboBoxModel<String> itemComboxGioiTinhKH = new DefaultComboBoxModel<>();
        itemComboxGioiTinhKH.addElement("Nam");
        itemComboxGioiTinhKH.addElement("Nữ");
        cbxGioiTinhQL.setModel(itemComboxGioiTinhKH);
        cbxGioiTinhQL.setSelectedIndex(-1);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setVisible(true);
        hienThiDanhSachKhachHang();
        resetCapNhat();
    }

    private void hienThiDanhSachKhachHang() {
        try {
            dtmQuanLyKhachHang = hienThiDanhSach(bllKhachHang.layToanBoKhachHang());
            tblQuanLyKhachHang.setModel(dtmQuanLyKhachHang);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private DefaultTableModel hienThiDanhSach(ArrayList<KhachHang> ds) {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Mã khách hàng");
        dtm.addColumn("Tên khách hàng");
        dtm.addColumn("Giới tính");
        dtm.addColumn("SĐT");
        dtm.addColumn("CMND");
        dtm.addColumn("Địa chỉ");
        for (KhachHang kh : ds) {
            Vector<String> v = new Vector<>();
            v.add(kh.getMaKhachHang());
            v.add(kh.getTenKhachHang());
            v.add(kh.getGioiTinh());
            v.add(kh.getSdt());
            v.add(kh.getCmnd());
            v.add(kh.getDiaChi());
            dtm.addRow(v);
        }
        return dtm;
    }

    private void resetCapNhat() {
        txtMaKhachHangQL.setText(taoMa.layMaKhachHangTiepTheo());
        txtTenKhachHangQL.setText("");
        cbxGioiTinhQL.setSelectedIndex(-1);
        txtPhoneQL.setText("");
        txtCMNDQL.setText("");
        txtDiaChiQL.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaKhachHangQL = new javax.swing.JTextField();
        txtTenKhachHangQL = new javax.swing.JTextField();
        txtPhoneQL = new javax.swing.JTextField();
        txtCMNDQL = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDiaChiQL = new javax.swing.JTextField();
        cbxGioiTinhQL = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblQuanLyKhachHang = new javax.swing.JTable();
        btnTimKiem = new javax.swing.JButton();
        btnThemKhachHang = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnSuaKhachHang = new javax.swing.JButton();
        btnXoaKhachHang = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnTimKiemInRaFIle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin Khách Hàng:"));

        jLabel2.setText("Mã Khách Hàng:");

        jLabel3.setText("Tên Khách Hàng:");

        jLabel4.setText("Giới Tính:");

        jLabel5.setText("Phone:");

        jLabel6.setText("CMND:");

        jLabel7.setText("Địa Chỉ:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenKhachHangQL, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(txtPhoneQL)
                    .addComponent(txtCMNDQL)
                    .addComponent(txtDiaChiQL)
                    .addComponent(txtMaKhachHangQL, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbxGioiTinhQL, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMaKhachHangQL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTenKhachHangQL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(cbxGioiTinhQL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPhoneQL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(txtCMNDQL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDiaChiQL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Kết Quả:"));
        jPanel11.setLayout(new java.awt.BorderLayout());

        tblQuanLyKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQuanLyKhachHangMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblQuanLyKhachHangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblQuanLyKhachHangMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tblQuanLyKhachHang);

        jPanel11.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnThemKhachHang.setText("Thêm Khách Hàng");
        btnThemKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemKhachHangActionPerformed(evt);
            }
        });

        jButton1.setText("Thêm Từ File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnSuaKhachHang.setText("Sửa Khách Hàng");
        btnSuaKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaKhachHangActionPerformed(evt);
            }
        });

        btnXoaKhachHang.setText("Xóa Khách hàng");
        btnXoaKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaKhachHangActionPerformed(evt);
            }
        });

        jButton3.setText("Xem Toàn Bộ Khách Hàng");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Làm Sạch Dữ Liệu Nhập");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnTimKiemInRaFIle.setText("In Ra File");
        btnTimKiemInRaFIle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemInRaFIleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTimKiemInRaFIle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThemKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSuaKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXoaKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTimKiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThemKhachHang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSuaKhachHang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoaKhachHang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTimKiemInRaFIle)
                        .addContainerGap(65, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblQuanLyKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQuanLyKhachHangMouseClicked

    }//GEN-LAST:event_tblQuanLyKhachHangMouseClicked

    private void tblQuanLyKhachHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQuanLyKhachHangMousePressed
        // TODO add your handling code here:
        int row = tblQuanLyKhachHang.getSelectedRow();
        String maKhachHang = tblQuanLyKhachHang.getValueAt(row, 0) + "";
        String tenKhachHang = tblQuanLyKhachHang.getValueAt(row, 1) + "";
        String gioiTinh = tblQuanLyKhachHang.getValueAt(row, 2) + "";
        String phone = tblQuanLyKhachHang.getValueAt(row, 3) + "";
        String cmnd = tblQuanLyKhachHang.getValueAt(row, 4) + "";
        String diaChi = tblQuanLyKhachHang.getValueAt(row, 5) + "";
        maKhachHang = maKhachHang.trim();
        gioiTinh = gioiTinh.trim();
        cmnd = cmnd.trim();
        txtMaKhachHangQL.setText(maKhachHang);
        txtTenKhachHangQL.setText(tenKhachHang);
        txtPhoneQL.setText(phone);
        txtCMNDQL.setText(cmnd);
        txtDiaChiQL.setText(diaChi);
        if (gioiTinh.equalsIgnoreCase("Nam")) {
            cbxGioiTinhQL.setSelectedIndex(0);
        } else {
            cbxGioiTinhQL.setSelectedIndex(1);
        }
    }//GEN-LAST:event_tblQuanLyKhachHangMousePressed

    private void tblQuanLyKhachHangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQuanLyKhachHangMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblQuanLyKhachHangMouseReleased

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        String maKhachHang = txtMaKhachHangQL.getText();
        String tenKhachHang = txtTenKhachHangQL.getText();
        String sdt = txtPhoneQL.getText();
        String cmnd = txtCMNDQL.getText();
        String diaChi = txtDiaChiQL.getText();
        String gioiTinh = "";
        if (cbxGioiTinhQL.getSelectedIndex() != -1) {
            gioiTinh = cbxGioiTinhQL.getSelectedItem().toString();
        }
        if (maKhachHang.equals("") && tenKhachHang.equals("") && cbxGioiTinhQL.getSelectedIndex() == -1 && sdt.equals("") && cmnd.equals("") && diaChi.equals("")) {
            JOptionPane.showMessageDialog(null, "Chưa nhập dữ liệu");
            return;
        } else if (!sdt.matches("\\d+|\\s*")) {
            JOptionPane.showMessageDialog(null, "Nhập sai số điện thoại");
            return;
        } else if (!sdt.matches("\\d{12}|\\s*")) {
            JOptionPane.showMessageDialog(null, "Nhập sai số điện thoại");
            return;
        } else {
            ArrayList<KhachHang> ds = null;
            try {
                ds = bllKhachHang.timKiemKhachHang(maKhachHang, tenKhachHang, gioiTinh, sdt, cmnd, diaChi);
            } catch (Exception ex) {
                ex.getStackTrace();
            }
            dtmTimKiemKhachHang = hienThiDanhSach(ds);
            tblQuanLyKhachHang.setModel(dtmTimKiemKhachHang);
            btnLast = btnTimKiem;
        }

    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnThemKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemKhachHangActionPerformed
        // TODO add your handling code here:
        String maKhachHang = txtMaKhachHangQL.getText();
        String tenKhachHang = txtTenKhachHangQL.getText();
        String sdt = txtPhoneQL.getText();
        String cmnd = txtCMNDQL.getText();
        String diaChi = txtDiaChiQL.getText();
        String gioiTinh = "";
        if (cbxGioiTinhQL.getSelectedIndex() != -1) {
            gioiTinh = cbxGioiTinhQL.getSelectedItem().toString();
        }
        String kiemTra = KiemTraDuLieuNhapThoaMan.kiemTraDuLieuNhapCapNhatKhachHang(tenKhachHang, gioiTinh, sdt, cmnd, diaChi);
        if (kiemTra.equals("Chưa nhập dữ liệu")) {
            JOptionPane.showMessageDialog(null, "Chưa nhập dữ liệu");
            return;
        }
        if (kiemTra.equals("Chưa nhập tên khách hàng")) {
            JOptionPane.showMessageDialog(null, "Chưa nhập tên khách hàng");
            return;
        }
        if (kiemTra.equals("Chưa chọn giới tính")) {
            JOptionPane.showMessageDialog(null, "Chưa chọn giới tính");
            return;
        }
        if (kiemTra.equals("Chưa nhập sđt")) {
            JOptionPane.showMessageDialog(null, "Chưa nhập sđt");
            return;
        }
        if (kiemTra.equals(sdt + " không phải số điện thoại")) {
            JOptionPane.showMessageDialog(null, "Nhập sai sđt");
            return;
        }
        if (kiemTra.equals("Chưa nhập CMND")) {
            JOptionPane.showMessageDialog(null, "Chưa nhập CMND");
            return;
        }
        if (kiemTra.equals("CMND phải có 9 hoặc 12 số")) {
            JOptionPane.showMessageDialog(null, "CMND phải có 9 hoặc 12 số");
            return;
        }
        if (kiemTra.equals("Chưa nhập địa chỉ")) {
            JOptionPane.showMessageDialog(null, "Chưa nhập địa chỉ");
            return;
        }
        if (kiemTra.equals("Dữ liệu thỏa mãn")) {
            int kt = JOptionPane.showConfirmDialog(null, "Bạn có muốn thêm không ?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (kt == JOptionPane.YES_OPTION) {
                int kq = 0;
                try {
                    kq = bllKhachHang.themKhachHang(maKhachHang, tenKhachHang, gioiTinh, sdt, cmnd, diaChi);
                    System.out.println(kq);
                    if (kq > 0) {
                        JOptionPane.showMessageDialog(null, "Thêm thành công");
                        hienThiDanhSachKhachHang();
                        tblQuanLyKhachHang.setModel(dtmQuanLyKhachHang);
                    } else {
                        JOptionPane.showMessageDialog(null, "Thêm thất bại");
                    }
                    resetCapNhat();
                } catch (Exception ex) {
                    ex.getStackTrace();
                }
            }
        }
    }//GEN-LAST:event_btnThemKhachHangActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSuaKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaKhachHangActionPerformed
        // TODO add your handling code here:
        int row = tblQuanLyKhachHang.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Chưa chọn dữ liệu cần sửa");
            return;
        }
        String maKhachHang = txtMaKhachHangQL.getText();
        String tenKhachHang = txtTenKhachHangQL.getText();
        String sdt = txtPhoneQL.getText();
        String cmnd = txtCMNDQL.getText();
        String diaChi = txtDiaChiQL.getText();
        String gioiTinh = "";
        if (cbxGioiTinhQL.getSelectedIndex() != -1) {
            gioiTinh = cbxGioiTinhQL.getSelectedItem().toString();
        }
        String kiemTra = KiemTraDuLieuNhapThoaMan.kiemTraDuLieuNhapCapNhatKhachHang(tenKhachHang, gioiTinh, sdt, cmnd, diaChi);
        if (kiemTra.equals("Chưa nhập dữ liệu")) {
            JOptionPane.showMessageDialog(null, "Chưa nhập dữ liệu");
            return;
        }
        if (kiemTra.equals("Chưa nhập tên khách hàng")) {
            JOptionPane.showMessageDialog(null, "Chưa nhập tên khách hàng");
            return;
        }
        if (kiemTra.equals("Chưa chọn giới tính")) {
            JOptionPane.showMessageDialog(null, "Chưa chọn giới tính");
            return;
        }
        if (kiemTra.equals("Chưa nhập sđt")) {
            JOptionPane.showMessageDialog(null, "Chưa nhập sđt");
            return;
        }
        if (kiemTra.equals(sdt + " không phải số điện thoại")) {
            JOptionPane.showMessageDialog(null, "Nhập sai sđt");
            return;
        }
        if (kiemTra.equals("Chưa nhập CMND")) {
            JOptionPane.showMessageDialog(null, "Chưa nhập CMND");
            return;
        }
        if (kiemTra.equals("CMND phải có 12 số")) {
            JOptionPane.showMessageDialog(null, "CMND phải có 9 hoặc 12 số");
            return;
        }
        if (kiemTra.equals("Chưa nhập địa chỉ")) {
            JOptionPane.showMessageDialog(null, "Chưa nhập địa chỉ");
            return;
        }
        if (kiemTra.equals("Dữ liệu thỏa mãn")) {
            int kt = JOptionPane.showConfirmDialog(null, "Bạn có muốn sửa không ?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (kt == JOptionPane.YES_OPTION) {
                int kq = 0;
                try {
                    kq = bllKhachHang.suaKhachHang(maKhachHang, tenKhachHang, gioiTinh, sdt, cmnd, diaChi);
                    System.out.println(kq);
                    if (kq > 0) {
                        JOptionPane.showMessageDialog(null, "Sửa thành công");
                        hienThiDanhSachKhachHang();
                        tblQuanLyKhachHang.setModel(dtmQuanLyKhachHang);
                    } else {
                        JOptionPane.showMessageDialog(null, "Sửa thất bại thất bại");
                    }
                    resetCapNhat();
                } catch (Exception ex) {
                    ex.getStackTrace();
                }
            }
        }
    }//GEN-LAST:event_btnSuaKhachHangActionPerformed

    private void btnXoaKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaKhachHangActionPerformed
        // TODO add your handling code here:
        int[] row = tblQuanLyKhachHang.getSelectedRows();
        if (row.length > 0) {
            int soLuong = 0;
            int kt = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa khách hàng", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (kt != JOptionPane.YES_OPTION) {
                return;
            }
            for (int r : row) {
                KhachHang kh = new KhachHang();
                kh.setMaKhachHang(tblQuanLyKhachHang.getValueAt(r, 0) + "");
                soLuong += bllKhachHang.xoaKhachHnag(kh);
            }
            if (soLuong <= 0) {
                JOptionPane.showMessageDialog(null, "Xóa thất bại");
                return;
            }
            JOptionPane.showMessageDialog(null, "Xóa thành công " + soLuong + "/" + row.length + " khách hàng");
            resetCapNhat();
            hienThiDanhSachKhachHang();
            tblQuanLyKhachHang.setModel(dtmQuanLyKhachHang);
        } else {
            JOptionPane.showMessageDialog(null, "Chưa chọn dữ liệu cần xóa");
            return;
        }
    }//GEN-LAST:event_btnXoaKhachHangActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        hienThiDanhSachKhachHang();
        tblQuanLyKhachHang.setModel(dtmQuanLyKhachHang);
        btnLast = jButton3;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        resetCapNhat();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnTimKiemInRaFIleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemInRaFIleActionPerformed
        // TODO add your handling code here:
        if (btnLast == btnTimKiem || btnLast == jButton3) {
            if (btnLast == jButton3) {
                JOptionPane.showMessageDialog(null, "<html><p>Đang chuẩn bị in kết quả tìm kiếm.</p>"
                        + "<p>Vui lòng nhấn ok và đợi trong giây lát.</p></html>");
                printKhachHang.inDanhSachKhachHang();
            } else {
                String maKhachHang = txtMaKhachHangQL.getText().trim();
                String tenKhachHang = txtTenKhachHangQL.getText();
                String phone = txtPhoneQL.getText().trim();
                String gioiTinh = "";
                if (cbxGioiTinhQL.getSelectedIndex() == 0) {
                    gioiTinh = "Nam";
                } else if (cbxGioiTinhQL.getSelectedIndex() == 1) {
                    gioiTinh = "Nữ";
                }
                String cmnd = txtCMNDQL.getText().trim();
                String diaChi = txtDiaChiQL.getText();
                JOptionPane.showMessageDialog(null, "<html><p>Đang chuẩn bị in kết quả tìm kiếm.</p>"
                        + "<p>Vui lòng nhấn ok và đợi trong giây lát.</p></html>");
                printKhachHang.inKetQuaTimKiemKhachHang("%" + maKhachHang + "%", "%" + tenKhachHang + "%", "%" + gioiTinh + "%", "%" + phone + "%", "%" + cmnd + "%", "%" + diaChi + "%");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Hãy tìm kiếm trước");
        }
    }//GEN-LAST:event_btnTimKiemInRaFIleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhachHangUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhachHangUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhachHangUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhachHangUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyKhachHangUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaKhachHang;
    private javax.swing.JButton btnThemKhachHang;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnTimKiemInRaFIle;
    private javax.swing.JButton btnXoaKhachHang;
    private javax.swing.JComboBox<String> cbxGioiTinhQL;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblQuanLyKhachHang;
    private javax.swing.JTextField txtCMNDQL;
    private javax.swing.JTextField txtDiaChiQL;
    private javax.swing.JTextField txtMaKhachHangQL;
    private javax.swing.JTextField txtPhoneQL;
    private javax.swing.JTextField txtTenKhachHangQL;
    // End of variables declaration//GEN-END:variables
}
