/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import controller.BLLPhong;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import model.printPhong;
import object.LoaiPhong;
import object.Phong;
import object.TinhTrangPhong;

/**
 *
 * @author Nguyen Hoang Giang
 */
public class QuanLyPhong extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyPhong
     */
    JButton btnLasted;

    public QuanLyPhong() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception ex) {
        }
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        hienThiToanBoTinhTrangPhong();
        hienThiToanBoLoaiPhong();
        hienThiDanhSachPhong(controller.BLLPhong.layToanBoDanhSachPhong());
        resetDuLieu();
    }

    private void resetDuLieu() {
        txtMaPhong.setText("");
        txtTenPhong.setText("");
        txtGiaPhong.setText("");
        cbxTinhTrang.setSelectedIndex(-1);
        cbxLoaiPhong.setSelectedIndex(-1);
    }

    private void hienThiToanBoLoaiPhong() {
        ArrayList<LoaiPhong> ds = controller.BLLPhong.layToanBoLoaiPhongs();
        DefaultComboBoxModel dcbxLoaiPhong = new DefaultComboBoxModel();
        for (LoaiPhong loaiPhong : ds) {
            dcbxLoaiPhong.addElement(loaiPhong);
        }
        cbxLoaiPhong.setModel(dcbxLoaiPhong);
    }

    private void hienThiToanBoTinhTrangPhong() {
        ArrayList<TinhTrangPhong> ds = controller.BLLPhong.layToanBoTinhTrangPhong();
        DefaultComboBoxModel dcbxTinhTrang = new DefaultComboBoxModel();
        for (TinhTrangPhong tt : ds) {
            dcbxTinhTrang.addElement(tt);
        }
        cbxTinhTrang.setModel(dcbxTinhTrang);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaPhong = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTenPhong = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbxLoaiPhong = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbxTinhTrang = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtGiaPhong = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhong = new javax.swing.JTable();
        btnTimKiem = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLamSach = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin Phòng:"));

        jLabel1.setText("Mã Phòng:");

        jLabel2.setText("Tên Phòng:");

        jLabel3.setText("Loại Phòng:");

        cbxLoaiPhong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxLoaiPhongItemStateChanged(evt);
            }
        });

        jLabel4.setText("Tình Trạng Phòng:");

        jLabel5.setText("Giá Phòng:");

        txtGiaPhong.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaPhong)
                    .addComponent(txtTenPhong)
                    .addComponent(cbxLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGiaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbxTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGiaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Kết Quả:"));
        jPanel3.setLayout(new java.awt.BorderLayout());

        tblPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblPhongMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblPhong);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm Phòng");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa Phòng");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa Phòng");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnLamSach.setText("Làm Sạch Dữ Liệu");
        btnLamSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamSachActionPerformed(evt);
            }
        });

        jButton1.setText("In Kết Quả Tìm Kiếm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLamSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimKiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLamSach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxLoaiPhongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxLoaiPhongItemStateChanged
        // TODO add your handling code here:
        if (cbxLoaiPhong.getSelectedIndex() != -1) {
            LoaiPhong loaiPhong = (LoaiPhong) cbxLoaiPhong.getSelectedItem();
            txtGiaPhong.setText(loaiPhong.getGiaLoaiPhong() + "VND");
        }
    }//GEN-LAST:event_cbxLoaiPhongItemStateChanged

    private void tblPhongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhongMousePressed
        // TODO add your handling code here:
        int row = tblPhong.getSelectedRow();
        txtMaPhong.setText(tblPhong.getValueAt(row, 0) + "");
        txtTenPhong.setText(tblPhong.getValueAt(row, 1) + "");
        String maLoaiPhong = tblPhong.getValueAt(row, 2) + "";
        String maTinhTrang = tblPhong.getValueAt(row, 3) + "";
        if (maLoaiPhong.equalsIgnoreCase("Phòng Vip")) {
            cbxLoaiPhong.setSelectedIndex(0);
        } else if (maLoaiPhong.equalsIgnoreCase("Phòng Đơn")) {
            cbxLoaiPhong.setSelectedIndex(1);
        } else if (maLoaiPhong.equalsIgnoreCase("Phòng Đôi")) {
            cbxLoaiPhong.setSelectedIndex(2);
        }
        if (maTinhTrang.equalsIgnoreCase("Sẵn Sàng")) {
            cbxTinhTrang.setSelectedIndex(0);
        } else if (maTinhTrang.equalsIgnoreCase("Đang Có Khách")) {
            cbxTinhTrang.setSelectedIndex(1);
        } else if (maTinhTrang.equalsIgnoreCase("Đang Dọn Dẹp")) {
            cbxTinhTrang.setSelectedIndex(2);
        } else if (maTinhTrang.equalsIgnoreCase("Đang Sửa Chữa")) {
            cbxTinhTrang.setSelectedIndex(3);
        } else if (maTinhTrang.equalsIgnoreCase("Đang Dọn Dep")) {
            cbxTinhTrang.setSelectedIndex(4);
        }
    }//GEN-LAST:event_tblPhongMousePressed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        String maPhong = txtMaPhong.getText();
        String tenPhong = txtTenPhong.getText();
        String maLoaiPhong;
        String maTinhTrang;
        if (cbxLoaiPhong.getSelectedIndex() != -1) {
            LoaiPhong loaiPhong = (LoaiPhong) cbxLoaiPhong.getSelectedItem();
            maLoaiPhong = loaiPhong.getMaLoaiPhong();
        } else {
            maLoaiPhong = "";
        }
        if (cbxTinhTrang.getSelectedIndex() != -1) {
            TinhTrangPhong tinhTrang = (TinhTrangPhong) cbxTinhTrang.getSelectedItem();
            maTinhTrang = tinhTrang.getMaTinhTrang();
        } else {
            maTinhTrang = "";
        }
        if (kiemTraDuLieuTimKiem()) {
            hienThiDanhSachPhong(controller.BLLPhong.timKiemPhong("%" + maPhong + "%", "%" + tenPhong + "%", "%" + maLoaiPhong + "%", "%" + maTinhTrang + "%"));
            btnLasted = btnTimKiem;
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        int xacNhan = JOptionPane.showConfirmDialog(null, "Bạn muốn thêm phòng ?", "Xác nhận", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (xacNhan != JOptionPane.YES_OPTION) {
            return;
        }
        if (kiemTraDULieuNhap()) {
            String maPhong = txtMaPhong.getText();
            String tenPhong = txtTenPhong.getText();
            LoaiPhong loaiPhong = (LoaiPhong) cbxLoaiPhong.getSelectedItem();
            String maLoaiPhong = loaiPhong.getMaLoaiPhong();
            String maTinhTrang;
            TinhTrangPhong tinhTrang = (TinhTrangPhong) cbxTinhTrang.getSelectedItem();
            maTinhTrang = tinhTrang.getMaTinhTrang();
            int kq = controller.BLLPhong.themPhong(maPhong, tenPhong, maLoaiPhong, maTinhTrang);
            if (kq > 0) {
                JOptionPane.showMessageDialog(null, "Thêm thành công");
                hienThiDanhSachPhong(controller.BLLPhong.layToanBoDanhSachPhong());
                btnLasted = btnThem;
                resetDuLieu();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Thêm thất bại");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if (kiemTraDULieuNhap()) {
            int xacNhan = JOptionPane.showConfirmDialog(null, "Bạn có muốn sửa ?", "Xác nhân sửa", JOptionPane.YES_NO_OPTION);
            if (xacNhan == JOptionPane.YES_OPTION) {
                String maPhong = txtMaPhong.getText();
                String tenPhong = txtTenPhong.getText();
                LoaiPhong loaiPhong = (LoaiPhong) cbxLoaiPhong.getSelectedItem();
                TinhTrangPhong tinhTrang = (TinhTrangPhong) cbxTinhTrang.getSelectedItem();
                String maLoaiPhong = loaiPhong.getMaLoaiPhong();
                String maTinhTrang = tinhTrang.getMaTinhTrang();
                int kq = BLLPhong.suaPhong(maPhong, tenPhong, maLoaiPhong, maTinhTrang);
                if (kq > 0) {
                    JOptionPane.showMessageDialog(null, "Sửa thành công");
                    hienThiDanhSachPhong(BLLPhong.layToanBoDanhSachPhong());
                    btnLasted = btnSua;
                } else {
                    JOptionPane.showMessageDialog(null, "Sửa thất bại");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Sửa thất bại");
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int[] rows = tblPhong.getSelectedRows();
        if (rows.length > 0) {
            int kt = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa phòng ?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
            if (kt == JOptionPane.YES_OPTION) {
                int soLuong = 0;
                for (int i : rows) {
                    String maPhong = tblPhong.getValueAt(i, 0) + "";
                    soLuong += BLLPhong.xoaPhong(maPhong);
                }
                if (soLuong > 0) {
                    JOptionPane.showMessageDialog(null, "Xóa thành công " + soLuong + " phòng");
                    hienThiDanhSachPhong(BLLPhong.layToanBoDanhSachPhong());
                    btnLasted = btnXoa;
                    resetDuLieu();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Xóa thất bại");
                return;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Chưa chọn phòng cần xóa");
            return;
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private boolean kiemTraDuLieuTimKiem() {
        String maPhong = txtMaPhong.getText();
        String tenPhong = txtTenPhong.getText();
        String maLoaiPhong;
        String maTinhTrang;
        if (cbxLoaiPhong.getSelectedIndex() != -1) {
            LoaiPhong loaiPhong = (LoaiPhong) cbxLoaiPhong.getSelectedItem();
            maLoaiPhong = loaiPhong.getMaLoaiPhong();
        } else {
            maLoaiPhong = "";
        }
        if (cbxTinhTrang.getSelectedIndex() != -1) {
            TinhTrangPhong tinhTrang = (TinhTrangPhong) cbxTinhTrang.getSelectedItem();
            maTinhTrang = tinhTrang.getMaTinhTrang();
        } else {
            maTinhTrang = "";
        }
        String regex = "\\s*";
        if (maPhong.matches(regex) && tenPhong.matches(regex) && maLoaiPhong.matches(regex) && maTinhTrang.matches(regex)) {
            JOptionPane.showMessageDialog(null, "Chưa nhập dữ liệu tìm kiếm");
            return false;
        }
        return true;
    }

    private void hienThiDanhSachPhong(ArrayList<Phong> ds) {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Mã Phòng");
        dtm.addColumn("Tên Phòng");
        dtm.addColumn("Loại Phòng");
        dtm.addColumn("Tình Trạng");
        for (Phong p : ds) {
            Vector<String> v = new Vector<>();
            v.add(p.getMaPhong());
            v.add(p.getTenPhong());
            String maLoaiPhong = p.getMaLoaiPhong();
            String loaiPhong = "";

            if (maLoaiPhong.equalsIgnoreCase("LoaiPhong1")) {
                loaiPhong = "Phòng Vip";
            } else if (maLoaiPhong.equalsIgnoreCase("LoaiPhong2")) {
                loaiPhong = "Phòng Đơn";
            } else if (maLoaiPhong.equalsIgnoreCase("LoaiPhong3")) {
                loaiPhong = "Phòng Đôi";
            }
            v.add(loaiPhong);

            String tinhTrang = "";
            String maTinhTrang = p.getMaTinhTrang();
            if (maTinhTrang.equalsIgnoreCase("TinhTrang01")) {
                tinhTrang = "Sẵn Sàng";
            } else if (maTinhTrang.equalsIgnoreCase("TinhTrang02")) {
                tinhTrang = "Đang Có Khách";
            } else if (maTinhTrang.equalsIgnoreCase("TinhTrang03")) {
                tinhTrang = "Đang Dọn Dẹp";
            } else if (maTinhTrang.equalsIgnoreCase("TinhTrang04")) {
                tinhTrang = "Đang Sửa Chữa";
            } else if (maTinhTrang.equalsIgnoreCase("TinhTrang05")) {
                tinhTrang = "Đang Dọn Dẹp";
            }

            v.add(tinhTrang);
            dtm.addRow(v);
        }
        tblPhong.setModel(dtm);
    }

    private boolean kiemTraDULieuNhap() {
        String maPhong = txtMaPhong.getText();
        String tenPhong = txtTenPhong.getText();
        String maLoaiPhong;
        String maTinhTrang;
        if (cbxLoaiPhong.getSelectedIndex() != -1) {
            LoaiPhong loaiPhong = (LoaiPhong) cbxLoaiPhong.getSelectedItem();
            maLoaiPhong = loaiPhong.getMaLoaiPhong();
        } else {
            maLoaiPhong = "";
        }
        if (cbxTinhTrang.getSelectedIndex() != -1) {
            TinhTrangPhong tinhTrang = (TinhTrangPhong) cbxTinhTrang.getSelectedItem();
            maTinhTrang = tinhTrang.getMaTinhTrang();
        } else {
            maTinhTrang = "";
        }
        String regex = "\\s*";
        if (maPhong.matches(regex) && tenPhong.matches(regex) && maLoaiPhong.matches(regex) && maTinhTrang.matches(regex)) {
            JOptionPane.showMessageDialog(null, "Chưa nhập dữ liệu tìm kiếm");
            return false;
        }
        if (maPhong.matches(regex)) {
            JOptionPane.showMessageDialog(null, "Chưa nhập mã phòng");
            return false;
        }
        if (tenPhong.matches(regex)) {
            JOptionPane.showMessageDialog(null, "Chưa nhập tên phòng");
            return false;
        }
        if (maLoaiPhong.matches(regex)) {
            JOptionPane.showMessageDialog(null, "Chưa chọn loại phòng");
            return false;
        }
        if (maTinhTrang.matches(regex)) {
            JOptionPane.showMessageDialog(null, "Chưa chọn tình trạng phòng");
            return false;
        }
        return true;
    }

    private void btnLamSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamSachActionPerformed
        // TODO add your handling code here:
        resetDuLieu();
        btnLasted = btnLamSach;
    }//GEN-LAST:event_btnLamSachActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (btnLasted != btnTimKiem) {
            JOptionPane.showMessageDialog(null, "Hãy tìm kiếm trước");
        } else {
            String maPhong = txtMaPhong.getText();
            String tenPhong = txtTenPhong.getText();
            String maLoaiPhong = "";
            if (cbxLoaiPhong.getSelectedIndex() != -1) {
                LoaiPhong l = (LoaiPhong) cbxLoaiPhong.getSelectedItem();
                maLoaiPhong = l.getMaLoaiPhong();
            }
            String maTinhTrang = "";
            if (cbxTinhTrang.getSelectedIndex() != -1) {
                TinhTrangPhong t = (TinhTrangPhong) cbxTinhTrang.getSelectedItem();
                maTinhTrang = t.getMaTinhTrang();
            }
            printPhong.inKetQuaTimKiemPhong("%"+maPhong+"%","%"+ tenPhong+"%","%"+ maLoaiPhong+"%","%"+ maTinhTrang+"%");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyPhong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamSach;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbxLoaiPhong;
    private javax.swing.JComboBox<String> cbxTinhTrang;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPhong;
    private javax.swing.JTextField txtGiaPhong;
    private javax.swing.JTextField txtMaPhong;
    private javax.swing.JTextField txtTenPhong;
    // End of variables declaration//GEN-END:variables
}
