/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import controller.BLLKhachHang;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import model.printKhachHang;
import object.KhachHang;

/**
 *
 * @author Nguyen Hoang Giang
 */
public class ThongKeKhachHangUI extends javax.swing.JFrame {

    /**
     * Creates new form ThongKeKhachHangUI
     */
    BLLKhachHang bllKhachHang;
    JPanel pnLast;

    public ThongKeKhachHangUI() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception ex) {
        }
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        bllKhachHang = new BLLKhachHang();
        hienThiDanhSachKhachHang();
        hienThiThongKeTheoTen();
        hienThiThongKeTheoGioiTinh();
        hienThiThongKeTheoDiaChi();
    }

    private void hienThiDanhSachKhachHang() {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Mã Khách Hàn");
        dtm.addColumn("Tên Khách Hàng");
        dtm.addColumn("Giới Tính");
        dtm.addColumn("Số Điện Thoại");
        dtm.addColumn("Số CMND");
        dtm.addColumn("Địa Chỉ");
        ArrayList<KhachHang> ds = bllKhachHang.layToanBoKhachHang();
        for (KhachHang kh : ds) {
            Vector<String> v = new Vector<>();
            v.add(kh.getMaKhachHang());
            v.add(kh.getTenKhachHang());
            v.add(kh.getGioiTinh());
            v.add(kh.getSdt());
            v.add(kh.getCmnd());
            v.add(kh.getDiaChi());
            dtm.addRow(v);
        }
        tblDanhSachKhachHang.setModel(dtm);
    }

    private void hienThiThongKeTheoTen() {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("STT");
        dtm.addColumn("Tên Khách Hàng");
        dtm.addColumn("Số Lượng ( Khách Hàng )");
        int stt = 1;
        HashMap<String, Integer> ketQua = bllKhachHang.thongKeTheoTen();
        for (Map.Entry<String, Integer> m : ketQua.entrySet()) {
            Vector<String> v = new Vector<>();
            v.add(stt + "");
            v.add(m.getKey());
            v.add(m.getValue() + "");
            dtm.addRow(v);
            stt++;
        }
        tblthongKeTheoTen.setModel(dtm);
    }

    private void hienThiThongKeTheoGioiTinh() {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("STT");
        dtm.addColumn("Giới Tính");
        dtm.addColumn("Số Lượng ( Khách Hàng )");
        int stt = 1;
        HashMap<String, Integer> ketQua = bllKhachHang.thongKeTheoGioiTinh();
        for (Map.Entry<String, Integer> m : ketQua.entrySet()) {
            Vector<String> v = new Vector<>();
            v.add(stt + "");
            v.add(m.getKey());
            v.add(m.getValue() + "");
            dtm.addRow(v);
            stt++;
        }
        tblThongKeTheoGioiTinh.setModel(dtm);
    }

    private void hienThiThongKeTheoDiaChi() {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("STT");
        dtm.addColumn("Địa Chỉ");
        dtm.addColumn("Số Lượng ( Khách Hàng )");
        int stt = 1;
        HashMap<String, Integer> ketQua = bllKhachHang.thongKeTheoDiaChi();
        for (Map.Entry<String, Integer> m : ketQua.entrySet()) {
            Vector<String> v = new Vector<>();
            v.add(stt + "");
            v.add(m.getKey());
            v.add(m.getValue() + "");
            dtm.addRow(v);
            stt++;
        }
        tblThongKeTheoDiaChi.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnIn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSachKhachHang = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblthongKeTheoTen = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblThongKeTheoGioiTinh = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblThongKeTheoDiaChi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 480));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("THỐNG KÊ KHÁCH HÀNG");

        btnIn.setText("Xuất Ra File");
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIn, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 34, Short.MAX_VALUE)
                        .addComponent(btnIn))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.setLayout(new java.awt.BorderLayout());

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel4.setLayout(new java.awt.BorderLayout());

        tblDanhSachKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Khách Hàng", "Tên Khách Hàng", "Giới Tính", "Số Điện Thoại", "Số CMND", "Địa Chỉ"
            }
        ));
        jScrollPane1.setViewportView(tblDanhSachKhachHang);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Danh Sách Khách Hàng", jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        tblthongKeTheoTen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên Khách Hàng", "Số Lượng ( Khách Hàng )"
            }
        ));
        jScrollPane2.setViewportView(tblthongKeTheoTen);

        jPanel5.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Thống Kê Theo Tên", jPanel5);

        jPanel6.setLayout(new java.awt.BorderLayout());

        tblThongKeTheoGioiTinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Giới Tính", "Sô Lượng ( Khách Hàng )"
            }
        ));
        jScrollPane3.setViewportView(tblThongKeTheoGioiTinh);

        jPanel6.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Thống Kê Theo Giới Tính", jPanel6);

        jPanel7.setLayout(new java.awt.BorderLayout());

        tblThongKeTheoDiaChi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Địa Chỉ", "Số Lượng ( Khách Hàng )"
            }
        ));
        jScrollPane4.setViewportView(tblThongKeTheoDiaChi);

        jPanel7.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Thống Kê Theo Địa Chỉ", jPanel7);

        jPanel1.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        JPanel pn = (JPanel) jTabbedPane1.getSelectedComponent();
        pnLast = pn;
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void btnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInActionPerformed
        // TODO add your handling code here:
        if (pnLast == jPanel4) {
            JOptionPane.showMessageDialog(null, "<html><p>Đang chuẩn bị in danh sách khách hàng ...</p>"
                    + "<p>Vui lòng đợi trong giây lát");
            printKhachHang.inDanhSachKhachHang();
        } else if (pnLast == jPanel5) {
            JOptionPane.showMessageDialog(null, "<html><p>Đang chuẩn bị in thông tin thống kê theo tên ...</p>"
                    + "<p>Vui lòng đợi trong giây lát");
            printKhachHang.inThongKeTheoTen();
        } else if (pnLast == jPanel6) {
            JOptionPane.showMessageDialog(null, "<html><p>Đang chuẩn bị in thông tin thống kê theo giới tính ...</p>"
                    + "<p>Vui lòng đợi trong giây lát");
            printKhachHang.inThongKeTheoGioiTinh();
        } else if (pnLast == jPanel7) {
            JOptionPane.showMessageDialog(null, "<html><p>Đang chuẩn bị in thông tin thống kê theo địa chỉ ...</p>"
                    + "<p>Vui lòng đợi trong giây lát");
            printKhachHang.inThongKeTheoDiaChi();
        }
    }//GEN-LAST:event_btnInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKeKhachHangUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKeKhachHangUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKeKhachHangUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKeKhachHangUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKeKhachHangUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblDanhSachKhachHang;
    private javax.swing.JTable tblThongKeTheoDiaChi;
    private javax.swing.JTable tblThongKeTheoGioiTinh;
    private javax.swing.JTable tblthongKeTheoTen;
    // End of variables declaration//GEN-END:variables
}
